version: '3'

services:
  rdb-connector-posgresql:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    links:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD: "it-test-pw"
      - POSTGRES_USER: "it-test-user"
      - POSTGRES_DB: "it-test-db"
    cached: true
    volumes:
      - ./postgresql/ssl/root.crt:/var/lib/pgsql/data/root.crt
      - ./postgresql/ssl/server.crt:/var/lib/pgsql/data/server.crt
      - ./postgresql/ssl/server.key:/var/lib/pgsql/data/server.key
      - ./postgresql/postgresql.conf:/var/lib/pgsql/data/postgresql.conf
