version: '3'

services:
  rdb-connector-mssql:
    build: .
    cached: true
    environment:
      DATABASE_HOST: "db"
    links:
      - db

  db:
    image: microsoft/mssql-server-linux:2017-GA
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pwPW123!"
    cached: true