version: '3'

services:
  rdb-connector-postgresql:
    build: .
    cached: true
    links:
      - db

  db:
    build: ./postgresql
    environment:
      POSTGRES_PASSWORD: "it-test-pw"
      POSTGRES_USER: "it-test-user"
      POSTGRES_DB: "it-test-db"
    cached: true
