version: '3'

services:
  rdb-connector-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    links:
      - db

  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    cached: true
    volumes:
      - ./mysql/ssl:/etc/mysql
      - ./mysql/my.cnf:/etc/my.cnf
