version: '3'

services:
  rdb-allconnector:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    encrypted_env_file: itenv.encrypted

  rdb-mysql-connector-56:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    depends_on:
      - mysql-db-56
    encrypted_env_file: itenv.encrypted

  rdb-mysql-connector-57:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    depends_on:
      - mysql-db-57
    encrypted_env_file: itenv.encrypted

  rdb-mysql-connector-8:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    depends_on:
      - mysql-db-8
    encrypted_env_file: itenv.encrypted

  rdb-mssql-connector:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    depends_on:
      - mssql-db
    encrypted_env_file: itenv.encrypted

  rdb-postgresql-connector:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    depends_on:
      - postgresql-db
    encrypted_env_file: itenv.encrypted

  rdb-publisher:
    build:
      context: .
      dockerfile: Dockerfile
    cached: true
    encrypted_env_file: publisher.encrypted

  mysql-db-56:
    image: mysql/mysql-server:5.6
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    cached: true
    volumes:
      - ./mysql/mysql/ssl:/etc/mysql
      - ./mysql/mysql/my.cnf:/etc/my.cnf

  mysql-db-57:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    cached: true
    volumes:
      - ./mysql/mysql/ssl:/etc/mysql
      - ./mysql/mysql/my.cnf:/etc/my.cnf

  mysql-db-8:
    image: mysql/mysql-server:8.0.14
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    cached: true
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./mysql/mysql/ssl:/etc/mysql
      - ./mysql/mysql/my.cnf:/etc/my.cnf

  mssql-db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pwPW123!"
      MSSQL_DB: "it_test_db"
      MSSQL_USER: "it_test_user"
      MSSQL_PASSWORD: "it_test_PW_1!"
    cached: true
    volumes:
    - ./mssql/mssql/mssql.conf:/var/opt/mssql/mssql.conf:ro
    - ./mssql/mssql/mssql_db.key:/etc/ssl/private/mssql.key:ro
    - ./mssql/mssql/mssql_db.pem:/etc/ssl/certs/mssql.pem:ro
    - ./mssql/mssql/setup.sql:/usr/config/setup.sql

  postgresql-db:
    build: ./postgresql/postgresql
    environment:
      POSTGRES_PASSWORD: "it-test-pw"
      POSTGRES_USER: "it-test-user"
      POSTGRES_DB: "it-test-db"
    cached: true
