version: '3'

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql/ssl:/etc/mysql
      - ./mysql/mysql/my.cnf:/etc/my.cnf
  mysql-db-8:
    image: mysql/mysql-server:8.0.14
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/mysql/ssl:/etc/mysql
      - ./mysql/mysql/my.cnf:/etc/my.cnf
  mssql-db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pwPW123!"
      MSSQL_DB: "it_test_db"
      MSSQL_USER: "it_test_user"
      MSSQL_PASSWORD: "it_test_PW_1!"
    ports:
    - "1433:1433"
    volumes:
    - ./mssql/mssql/mssql.conf:/var/opt/mssql/mssql.conf:ro
    - ./mssql/mssql/mssql_db.key:/etc/ssl/private/mssql.key:ro
    - ./mssql/mssql/mssql_db.pem:/etc/ssl/certs/mssql.pem:ro
    - ./mssql/mssql/setup.sql:/usr/config/setup.sql
  postgresql-db:
    build: ./postgresql/postgresql
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "it-test-pw"
      POSTGRES_USER: "it-test-user"
      POSTGRES_DB: "it-test-db"
