version: '3'

services:
  mysql-db:
    build:
      context: ./mysql/docker
      args:
        MYSQL_VERSION: 5.7.23
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    ports:
      - "3306:3306"

  mysql-db-8:
    build:
      context: ./mysql/docker
      args:
        MYSQL_VERSION: 8.0.14
    environment:
      MYSQL_USER: "it-test-user"
      MYSQL_PASSWORD: "it-test-pw"
      MYSQL_DATABASE: "it-test-db"
      MYSQL_ROOT_PASSWORD: "it-test-root-pw"
    ports:
      - "3307:3306"

  mssql-db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pwPW123!"
      MSSQL_DB: "it_test_db"
      MSSQL_USER: "it_test_user"
      MSSQL_PASSWORD: "it_test_PW_1!"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql/docker/mssql.conf:/var/opt/mssql/mssql.conf:ro
      - ./mssql/docker/mssql_db.key:/etc/ssl/private/mssql.key:ro
      - ./mssql/docker/mssql_db.pem:/etc/ssl/certs/mssql.pem:ro
      - ./mssql/docker/setup.sql:/usr/config/setup.sql

  postgresql-db:
    build: ./postgresql/docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "it-test-pw"
      POSTGRES_USER: "it-test-user"
      POSTGRES_DB: "it-test-db"
