version: '3'

services:
  db:
    build: ./postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "it-test-pw"
      POSTGRES_USER: "it-test-user"
      POSTGRES_DB: "it-test-db"
