version: '3'

services:
  db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pwPW123!"
      MSSQL_DB: "it_test_db"
      MSSQL_USER: "it_test_user"
      MSSQL_PASSWORD: "it_test_PW_1!"
    ports:
      - "1433:1433"