version: '3'

services:
  db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "pwPW123!"
      MSSQL_DB: "it_test_db"
      MSSQL_USER: "it_test_user"
      MSSQL_PASSWORD: "it_test_PW_1!"
    ports:
      - "1433:1433"
    volumes:
    - ./mssql/mssql.conf:/var/opt/mssql/mssql.conf:ro
    - ./mssql/mssql_db.key:/etc/ssl/private/mssql.key:ro
    - ./mssql/mssql_db.pem:/etc/ssl/certs/mssql.pem:ro
    - ./mssql/setup.sql:/usr/config/setup.sql
