addSbtPlugin("au.com.onegeek" %% "sbt-dotenv"  % "2.1.233")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"      % "2.1.1")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"   % "4.1.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt" % "2.3.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.26")
